[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "labelfree"
version = "0.0.1"
description = "Label-free Evaluation Metrics for Anomaly Detectors"
authors = [
  { name = "Oliver Hennhoefer", email = "oliver.hennhoefer@mail.de" },
]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
    "numpy~=2.2.5",
    "pandas~=2.2.3",
    "polars~=1.29.0",
    "scipy~=1.15.3"
]

[project.optional-dependencies]
dev = ["black", "ruff"]
examples = ["optuna"]
all = ["black", "ruff", "optuna"]

[project.urls]
"Homepage" = "https://github.com/OliverHennhoefer/label-free"
"Bugs" = "https://github.com/OliverHennhoefer/label-free/issues"
